github.com:
    users:
        merrittdigitalventures-arch:
            oauth_token: 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
    git_protocol: https
    user: merrittdigitalventures-arch
    oauth_token: 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
